import type { Metadata } from "next"; // a TypeScript type from Next.js. It helps describe page metadata like title and description.
import { Geist, Geist_Mono } from "next/font/google"; // Geist and Geist_Mono are fonts from Google Fonts that are used in the app.
import "./globals.css"; // ./globals.css imports the global CSS file so the whole app has access to it.

// font set up: configuring the Geist font to be used in the app
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// configuring the Geist Mono font to be used in the app
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// This metadata defines what shows up in the browser tab and search engine results
// such as the title of the website and its description.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The RootLayout is a special component in Next.js that wraps around everything in your app.
// It provides the main HTML structure (like <html> and <body> tags) that all other pages will be put inside of.
export default function RootLayout({
  children, // The "children" represents the content of the specific page you are currently viewing.
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* We apply the fonts we set up earlier to the body of our HTML document */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Here is where the actual content of each page will be displayed */}
        {children}
      </body>
    </html>
  );
}
